### ISSUE TITLE
Add mlab-ns privacy doc to this repo in MD format

### ISSUE THREAD

**Issue by critzo** [m-lab/mlab-ns#108]
The current mlab-ns privacy policy doc lives here:
https://docs.google.com/document/d/1NMPR86Wr6dHkQCnAjq_njK4CYM2naISrMxEZnMtDxUY/edit#heading=h.243v7fguv5iv

Move it into markdown format and include it in this repo.

**Comment by bassosimone** [comment]
I would love that! In the past, I had some luck converting Google Docs to Word files and then using pandoc to convert to Markdown and finally editing the result to make it what I wanted.

**Comment by critzo** [comment]
Completed.
