### ISSUE TITLE
Design Doc does not mention geo_options argument

### ISSUE THREAD

**Issue by rschulman** [m-lab/mlab-ns#111]
The Design Doc does not at the moment mention the fact that there is a geo_options policy argument to the URL, and obviously doesn't explain what that does.

**Comment by critzo** [comment]
This is the code that is used when calling mlab-ns with `geo_options`:
https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/resolver.py#L114-L134

**Comment by bassosimone** [comment]
I would say it would be safe to document this as:

> Chooses the N geographically closest servers to the client, where N is currently four.

No?
