### ISSUE TITLE
On overload return 204 or 429

### ISSUE THREAD

**Issue by bassosimone** [m-lab/mlab-ns#189]
This has been discussed by @stephen-soltesz and @bassosimone in https://github.com/m-lab/ndt-server/pull/109#pullrequestreview-233494749.

**Comment by pboothe** [comment]
Code changes are in. We'd like to get positive confirmation from onebox team before we deploy.

**Comment by stephen-soltesz** [comment]
The 204 change was deployed to prod yesterday. I suggest we reserve the 429 response for a future feature development.

**Comment by bassosimone** [comment]
Sure, thanks!

**Comment by bassosimone** [comment]
@stephen-soltesz can I close this issue now?

**Comment by bassosimone** [comment]
Closing this issue, as it seems done to me. We'll reopen it if required.
