### ISSUE TITLE
AppEngine daily cron job should be scheduled at beginning of day

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/mlab-ns#197]
Currently, the check_site cron job runs daily `every day 06:00`

We're updating the script-exporter-support repo to update daily at 15:00 UTC (~11AM ET) to occur in the morning of typical business hours.

We should do some thing similar to mlab-ns so we're not surprised after-hours by automated config changes.

**Comment by nkinkade** [comment]
This is done in PR #198. Closing.
