### ISSUE TITLE
Add support for legacy endpoints

### ISSUE THREAD

**Issue by bassosimone** [m-lab/mlab-ns#209]
@pboothe suggests to use `/dash` for github.com/neubot/dash and to implement a legacy alias such that `/neubot` (legacy endpoint) is an alias to `/dash` (new endpoint).

If we can assume that clients support redirect, then we can implement this using a redirect. It may perhaps be better and more robust to treat the name as an alias on the server side.

(I wonder how we could nudge users to switch to the new endpoint.)

**Comment by bassosimone** [comment]
After follow-up discussion with @pboothe we agreed that the name should stay `neubot` and the datatype will be `dash` because this is reasonable in terms of backwards compatibility.

**Comment by pboothe** [comment]
To be more specific, the experiment is named "neubot", and it produces the datatype "dash", similar to how we have the experiment "ndt" and it produces the datatypes "ndt5" and "ndt7"

**Comment by nkinkade** [comment]
This issue seems resolved. Should it be closed?

**Comment by pboothe** [comment]
This should be closed.
