### ISSUE TITLE
Remove tools that are not reported by Nagios

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#26]
If Nagios stops reporting status of a tool, mlab-ns should remove that tool from its list of tools/slices or at the very least alert. mlab_utility was removed in echo and mlab-ns continued reporting its last status even though it couldn't get updates for 3 months.

**Comment by nkinkade** [comment]
Closing this because we don't use Nagios any longer. Looks like it's time to do some issue pruning in this repo.
