### ISSUE TITLE
Nairobi is spelled Nairoby

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/mlab-ns#34]

**Comment by mtlynch** [comment]
Can you clarify? Where do you see this behavior?

**Comment by georgiamoon** [comment]
In the MeasureApp

On Tue, Jun 23, 2015 at 10:18 AM, mtlynch <notifications@github.com> wrote:

> Can you clarify? Where do you see this behavior?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-lab/mlab-ns/issues/34#issuecomment-114520309>.
>



-- 
Georgia Bullen
Open Technology Institute <http://newamerica.org/oti/> @ New America
<http://newamerica.org>
@georgiamoon <http://twitter.com/georgiamoon>

**Comment by mtlynch** [comment]
Can you provide repro instructions? I can't find anything in mlab-ns that would cause this behavior. This could be a MeaureApp bug. When I resolve a Nairobi site, I get the correct spelling:

http://mlab-nstesting.appspot.com/ndt?country=KE

**Comment by georgiamoon** [comment]
This may have actually been related to a MeasureApp bug that @collina fix.
What happened was that I loaded up MeasureApp and the first site I was
testing against was "Nairoby" which seemed weird both because of the
spelling and the fact that I was in DC.

@collina -- do you think this was actually just part of:
https://github.com/m-lab/measure-app/issues/13 ?
