### ISSUE TITLE
MaxMind database is out of date

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#44]
The mlab-ns MaxMind database is out of date. It looks like it uses a snapshot of MaxMind from September 2012. This affects all queries where the client specifies the `ip` parameter but the specified IP is not the client's actual IP. In cases where the client specifies an IP address in the `ip` parameter that matches the source IP address of the client request (i.e. `request.ip == request.remote_addr`), mlab-ns uses GAE geolocation and does not consult the MaxMind database.

@whh8b started working on a fix for this, but never completed the work. The partial fix is still available in his repo:
https://github.com/m-lab/mlab-ns/compare/master...whh8b:maxmind-rewrite-future

The strategy of the fix was (IIRC):
* Add a `timestamp` column to the MaxMind entries in the Cloud Datastore (e.g. `MaxmindCityBlock`)
* Change the IP geolocation in mlab-ns to use the entry with the highest timestamp when multiple entries match an IP address
* Add a cronjob to update Cloud Datastore with new MaxMind data every month
 * Purge all old timestamped entries after the update is complete

The idea was that we could replace the datastore while eliminating a window of downtime where one snapshot is removed and the next one is not yet loaded.

**Comment by nkinkade** [comment]
Is this right: "In cases where the client specifies their own IP address in the ip parameter, mlab-ns uses GAE geolocation and does not consult the MaxMind database."  I thought that this was only the case when request.ip == request.remote_addr, but if they [aren't equal](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/lookup_query.py#L91) mlab-ns uses MaxMind, not GAE geolocation.

**Comment by mtlynch** [comment]
Ah, ambiguous wording. I apologize. By "specifies their own" I meant "specifies an IP address that matches their own IP address." Updated for clarity, thanks!

**Comment by mtlynch** [comment]
Fixed in #46
