### ISSUE TITLE
mlab-ns loads mixed content over HTTPS

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#45]
mlab-ns' web interfaces load data from the Google charts API over plaintext HTTP even though the page is served over HTTPS, e.g.:

http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=3|FF0000|FF0000

Not sure if this is easily fixable as the https version of the above URL does not work.

**Comment by critzo** [comment]
This is available via HTTPS now. Fixing in an upcoming commit.
