### ISSUE TITLE
Remove workaround for ndt-ssl FQDN

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#48]
Long term, we plan to migrate all of our slice names to have M-Lab hosts use dashes instead of dots for parts of the hostname before `measurement-lab.org`. That is:

`ndt.iupui.mlab1.lga06.measurement-lab.org` -> `ndt-iupui-mlab1-lga06.measurement-lab.org`

ndt-ssl will be using this naming scheme first, so we temporarily have to special case ndt-ssl.

In the long term we should remove this special-case workaround. This bug tracks the work item to remove the workaround for ndt-ssl.

**Comment by nkinkade** [comment]
This is no longer really a special case. We convert the dotted names to dashed names for `ndt_ssl`, `ndt7` and `neubot_tls`.  It will probably be a very, very long time before we migrate to fully away from dotted names.
