### ISSUE TITLE
mlab-ns does not detect changes to existing sites

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#54]
mlab-ns does very light checking for changes to M-Lab sites. It only detects if a site is added, but doesn't detect changes such as:
- Site's metadata changed (e.g. site lat/lon)
- Site's set of slices changed

The workaround is to delete the site from the Datastore to force a refresh, but this is a manual task and temporarily puts the Datastore into an inconsistent state.

**Comment by mtlynch** [comment]
mlab-ns also needs to detect when a site gets retired (this might need to be a separate bug)

**Comment by kokosta** [comment]
Obsolete. Follow #126
