### ISSUE TITLE
mlab-ns for ndt only returning mlab1 server for each site 

### ISSUE THREAD

**Issue by kmmats** [m-lab/mlab-ns#56]
When hitting http://mlab-ns.appspot.com/ndt, it appears that under any policy we only ever get the mlab1 server returned. I would expect to see the full range of available servers per site.

**Comment by pboothe** [comment]
This is working as intended. MLab-NS has been changed to choose between the closest sites, and then always return the lexicographically first server that is up at the randomly chosen site.  This is fallout from https://www.measurementlab.net/blog/traffic-microbursts-and-their-effect-on-internet-measurement/
