### ISSUE TITLE
Automatically deploy to AppEngine on push to master

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#65]
Requiring developers to manually push to AppEngine to do updates is messy and error prone. We should add a clause to the Travis config so that merging into master automatically pushes to AppEngine. We have similar logic in the web site repo for pushing to S3:

https://github.com/m-lab/m-lab.github.io/blob/master/.travis.yml

**Comment by critzo** [comment]
Resolved in https://github.com/m-lab/mlab-ns/tree/v2017.07.31
