### ISSUE TITLE
Change the map to have one marker per site instead of one marker er city.

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#7]
(Migrated from code.google.com)
Reported by tiziana@measurementlab.net, Mar 10, 2013
mlan-ns' map (http://mlab-ns.appspot.com/admin/map) has one marker per each city with at least one site.

To facilitate per site monitoring in case of cities with more than one site, the map should have one marker per site.

**Comment by kokosta** [comment]
Obsolete
