### ISSUE TITLE
Failure to query Nagios after x attempts should trigger an alert

### ISSUE THREAD

**Issue by mtlynch** [m-lab/mlab-ns#81]
Currently failures to get updates to Nagios fail quietly and mlab-ns continues serving stale data. There should be loud alerts if mlab-ns is failing to get updates from Nagios.

**Comment by nkinkade** [comment]
This is now resolved by our migration away from Nagios to Prometheus. We have meaningful alerting for Prometheus metrics, and should they go down or missing, we get alerted. Closing issue.
